//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactorySuiteTools.wsFactorySuite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsFactorySuite.IServicioFactorySuite")]
    public interface IServicioFactorySuite {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioResponse")]
        FactorySuiteTools.wsFactorySuite.AutenticarUsuarioResponse AutenticarUsuario(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.AutenticarUsuarioResponse> AutenticarUsuarioAsync(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioTipoAutenticacionExtern" +
            "a", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioTipoAutenticacionExtern" +
            "aResponse")]
        string AutenticarUsuarioTipoAutenticacionExterna(string strTipoAutenticacion, string Usuario, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioTipoAutenticacionExtern" +
            "a", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioTipoAutenticacionExtern" +
            "aResponse")]
        System.Threading.Tasks.Task<string> AutenticarUsuarioTipoAutenticacionExternaAsync(string strTipoAutenticacion, string Usuario, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioFirmaDigital", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioFirmaDigitalResponse")]
        FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalResponse AutenticarUsuarioFirmaDigital(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioFirmaDigital", ReplyAction="http://tempuri.org/IServicioFactorySuite/AutenticarUsuarioFirmaDigitalResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalResponse> AutenticarUsuarioFirmaDigitalAsync(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/CerrarSesionUsuario", ReplyAction="http://tempuri.org/IServicioFactorySuite/CerrarSesionUsuarioResponse")]
        string CerrarSesionUsuario(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/CerrarSesionUsuario", ReplyAction="http://tempuri.org/IServicioFactorySuite/CerrarSesionUsuarioResponse")]
        System.Threading.Tasks.Task<string> CerrarSesionUsuarioAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerLista", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaResponse")]
        ActividadesLibreria.Design.Data.wsFactorySuite.empleado[] ObtenerLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerLista", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaResponse")]
        System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado[]> ObtenerListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaVacia", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaVaciaResponse")]
        ActividadesLibreria.Design.Data.wsFactorySuite.empleado[] ObtenerListaVacia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaVacia", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaVaciaResponse")]
        System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado[]> ObtenerListaVaciaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerEmpleadoResponse")]
        ActividadesLibreria.Design.Data.wsFactorySuite.empleado ObtenerEmpleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerEmpleadoResponse")]
        System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado> ObtenerEmpleadoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/ActualizarEmpleadoResponse")]
        void ActualizarEmpleado(int id, string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task ActualizarEmpleadoAsync(int id, string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/EliminarEmpleadoResponse")]
        void EliminarEmpleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task EliminarEmpleadoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoResponse")]
        int InsertarEmpleado(string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoResponse")]
        System.Threading.Tasks.Task<int> InsertarEmpleadoAsync(string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoClase", ReplyAction="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoClaseResponse")]
        ActividadesLibreria.Design.Data.wsFactorySuite.retorno InsertarEmpleadoClase(string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoClase", ReplyAction="http://tempuri.org/IServicioFactorySuite/InsertarEmpleadoClaseResponse")]
        System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.retorno> InsertarEmpleadoClaseAsync(string cedula, string nombre, int TipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EncriptarClaves", ReplyAction="http://tempuri.org/IServicioFactorySuite/EncriptarClavesResponse")]
        string EncriptarClaves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EncriptarClaves", ReplyAction="http://tempuri.org/IServicioFactorySuite/EncriptarClavesResponse")]
        System.Threading.Tasks.Task<string> EncriptarClavesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ActualizarEsquemaFormularios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ActualizarEsquemaFormulariosResponse")]
        void ActualizarEsquemaFormularios(string[] arrLlavesFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ActualizarEsquemaFormularios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ActualizarEsquemaFormulariosResponse")]
        System.Threading.Tasks.Task ActualizarEsquemaFormulariosAsync(string[] arrLlavesFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarReportes", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarReportesResponse")]
        FactorySuiteTools.wsFactorySuite.ListarReportesResponse ListarReportes(FactorySuiteTools.wsFactorySuite.ListarReportesRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarReportes", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarReportesResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarReportesResponse> ListarReportesAsync(FactorySuiteTools.wsFactorySuite.ListarReportesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ConsultarDatosReporte", ReplyAction="http://tempuri.org/IServicioFactorySuite/ConsultarDatosReporteResponse")]
        FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteResponse ConsultarDatosReporte(FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ConsultarDatosReporte", ReplyAction="http://tempuri.org/IServicioFactorySuite/ConsultarDatosReporteResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteResponse> ConsultarDatosReporteAsync(FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerReporteDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerReporteDesdeBDResponse")]
        FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDResponse ObtenerReporteDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerReporteDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerReporteDesdeBDResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDResponse> ObtenerReporteDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarReporte", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarReporteResponse")]
        void GuardarReporte(string IdReporte, byte[] baLayoutReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarReporte", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarReporteResponse")]
        System.Threading.Tasks.Task GuardarReporteAsync(string IdReporte, byte[] baLayoutReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarDashboards", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarDashboardsResponse")]
        FactorySuiteTools.wsFactorySuite.ListarDashboardsResponse ListarDashboards(FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarDashboards", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarDashboardsResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarDashboardsResponse> ListarDashboardsAsync(FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ConsultarDatosDashboard", ReplyAction="http://tempuri.org/IServicioFactorySuite/ConsultarDatosDashboardResponse")]
        FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardResponse ConsultarDatosDashboard(FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ConsultarDatosDashboard", ReplyAction="http://tempuri.org/IServicioFactorySuite/ConsultarDatosDashboardResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardResponse> ConsultarDatosDashboardAsync(FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerDashboardDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerDashboardDesdeBDResponse")]
        FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDResponse ObtenerDashboardDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerDashboardDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerDashboardDesdeBDResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDResponse> ObtenerDashboardDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarDashboard", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarDashboardResponse")]
        void GuardarDashboard(string IdDashboard, byte[] baLayoutDashboard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarDashboard", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarDashboardResponse")]
        System.Threading.Tasks.Task GuardarDashboardAsync(string IdDashboard, byte[] baLayoutDashboard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EjecutarOperacion", ReplyAction="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionResponse")]
        FactorySuiteTools.wsFactorySuite.EjecutarOperacionResponse EjecutarOperacion(FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EjecutarOperacion", ReplyAction="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.EjecutarOperacionResponse> EjecutarOperacionAsync(FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionMoviles", ReplyAction="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionMovilesResponse")]
        string[] EjecutarOperacionMoviles(string strXMLEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionMoviles", ReplyAction="http://tempuri.org/IServicioFactorySuite/EjecutarOperacionMovilesResponse")]
        System.Threading.Tasks.Task<string[]> EjecutarOperacionMovilesAsync(string strXMLEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarWorkflows", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarWorkflowsResponse")]
        FactorySuiteTools.wsFactorySuite.ListarWorkflowsResponse ListarWorkflows(FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ListarWorkflows", ReplyAction="http://tempuri.org/IServicioFactorySuite/ListarWorkflowsResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarWorkflowsResponse> ListarWorkflowsAsync(FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerWorkflowDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerWorkflowDesdeBDResponse")]
        FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDResponse ObtenerWorkflowDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerWorkflowDesdeBD", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerWorkflowDesdeBDResponse")]
        System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDResponse> ObtenerWorkflowDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarWorkflow", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarWorkflowResponse")]
        void GuardarWorkflow(string IdWorkflow, byte[] baLayoutWorkflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/GuardarWorkflow", ReplyAction="http://tempuri.org/IServicioFactorySuite/GuardarWorkflowResponse")]
        System.Threading.Tasks.Task GuardarWorkflowAsync(string IdWorkflow, byte[] baLayoutWorkflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaFormularios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaFormulariosResponse")]
        string ObtenerListaFormularios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaFormularios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaFormulariosResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaFormulariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaPrioridades", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaPrioridadesResponse")]
        string ObtenerListaPrioridades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaPrioridades", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaPrioridadesResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaPrioridadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaUsuarios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaUsuariosResponse")]
        string ObtenerListaUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaUsuarios", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaUsuariosResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaRoles", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaRolesResponse")]
        string ObtenerListaRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaRoles", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaRolesResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaPuestos", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaPuestosResponse")]
        string ObtenerListaPuestos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaPuestos", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaPuestosResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaPuestosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaComandos", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaComandosResponse")]
        string ObtenerListaComandos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaComandos", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaComandosResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaComandosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaEstadosProceso", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaEstadosProcesoResponse")]
        string ObtenerListaEstadosProceso(int IdWorkflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactorySuite/ObtenerListaEstadosProceso", ReplyAction="http://tempuri.org/IServicioFactorySuite/ObtenerListaEstadosProcesoResponse")]
        System.Threading.Tasks.Task<string> ObtenerListaEstadosProcesoAsync(int IdWorkflow);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string IdUsuario;
        
        public AutenticarUsuarioRequest() {
        }
        
        public AutenticarUsuarioRequest(string Usuario, string Clave, string Token, string IdUsuario) {
            this.Usuario = Usuario;
            this.Clave = Clave;
            this.Token = Token;
            this.IdUsuario = IdUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticarUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string IdUsuario;
        
        public AutenticarUsuarioResponse() {
        }
        
        public AutenticarUsuarioResponse(string AutenticarUsuarioResult, string Token, string IdUsuario) {
            this.AutenticarUsuarioResult = AutenticarUsuarioResult;
            this.Token = Token;
            this.IdUsuario = IdUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarUsuarioFirmaDigital", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarUsuarioFirmaDigitalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strFirmaDigital;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string IdUsuario;
        
        public AutenticarUsuarioFirmaDigitalRequest() {
        }
        
        public AutenticarUsuarioFirmaDigitalRequest(string Usuario, string Clave, string strFirmaDigital, string Token, string IdUsuario) {
            this.Usuario = Usuario;
            this.Clave = Clave;
            this.strFirmaDigital = strFirmaDigital;
            this.Token = Token;
            this.IdUsuario = IdUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarUsuarioFirmaDigitalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarUsuarioFirmaDigitalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticarUsuarioFirmaDigitalResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string IdUsuario;
        
        public AutenticarUsuarioFirmaDigitalResponse() {
        }
        
        public AutenticarUsuarioFirmaDigitalResponse(string AutenticarUsuarioFirmaDigitalResult, string Token, string IdUsuario) {
            this.AutenticarUsuarioFirmaDigitalResult = AutenticarUsuarioFirmaDigitalResult;
            this.Token = Token;
            this.IdUsuario = IdUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarReportes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarReportesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLDatos;
        
        public ListarReportesRequest() {
        }
        
        public ListarReportesRequest(string strToken, string strXMLDatos) {
            this.strToken = strToken;
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarReportesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarReportesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLDatos;
        
        public ListarReportesResponse() {
        }
        
        public ListarReportesResponse(string strXMLDatos) {
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDatosReporte", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarDatosReporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> RQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strParametrosPorResolver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] objDataSet;
        
        public ConsultarDatosReporteRequest() {
        }
        
        public ConsultarDatosReporteRequest(System.Collections.Generic.Dictionary<string, string> RQ, string strXMLDatos, string strParametrosPorResolver, byte[] objDataSet) {
            this.RQ = RQ;
            this.strXMLDatos = strXMLDatos;
            this.strParametrosPorResolver = strParametrosPorResolver;
            this.objDataSet = objDataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDatosReporteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarDatosReporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strParametrosPorResolver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] objDataSet;
        
        public ConsultarDatosReporteResponse() {
        }
        
        public ConsultarDatosReporteResponse(string strXMLDatos, string strParametrosPorResolver, byte[] objDataSet) {
            this.strXMLDatos = strXMLDatos;
            this.strParametrosPorResolver = strParametrosPorResolver;
            this.objDataSet = objDataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerReporteDesdeBD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerReporteDesdeBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strIdReporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] abReporte;
        
        public ObtenerReporteDesdeBDRequest() {
        }
        
        public ObtenerReporteDesdeBDRequest(string strIdReporte, byte[] abReporte) {
            this.strIdReporte = strIdReporte;
            this.abReporte = abReporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerReporteDesdeBDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerReporteDesdeBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] abReporte;
        
        public ObtenerReporteDesdeBDResponse() {
        }
        
        public ObtenerReporteDesdeBDResponse(byte[] abReporte) {
            this.abReporte = abReporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDashboards", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDashboardsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLDatos;
        
        public ListarDashboardsRequest() {
        }
        
        public ListarDashboardsRequest(string strToken, string strXMLDatos) {
            this.strToken = strToken;
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDashboardsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDashboardsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLDatos;
        
        public ListarDashboardsResponse() {
        }
        
        public ListarDashboardsResponse(string strXMLDatos) {
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDatosDashboard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarDatosDashboardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> RQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strParametrosPorResolver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] objDataSet;
        
        public ConsultarDatosDashboardRequest() {
        }
        
        public ConsultarDatosDashboardRequest(System.Collections.Generic.Dictionary<string, string> RQ, string strXMLDatos, string strParametrosPorResolver, byte[] objDataSet) {
            this.RQ = RQ;
            this.strXMLDatos = strXMLDatos;
            this.strParametrosPorResolver = strParametrosPorResolver;
            this.objDataSet = objDataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDatosDashboardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarDatosDashboardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strParametrosPorResolver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] objDataSet;
        
        public ConsultarDatosDashboardResponse() {
        }
        
        public ConsultarDatosDashboardResponse(string strXMLDatos, string strParametrosPorResolver, byte[] objDataSet) {
            this.strXMLDatos = strXMLDatos;
            this.strParametrosPorResolver = strParametrosPorResolver;
            this.objDataSet = objDataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDashboardDesdeBD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerDashboardDesdeBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strIdDashboard;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] abDashboard;
        
        public ObtenerDashboardDesdeBDRequest() {
        }
        
        public ObtenerDashboardDesdeBDRequest(string strIdDashboard, byte[] abDashboard) {
            this.strIdDashboard = strIdDashboard;
            this.abDashboard = abDashboard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDashboardDesdeBDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerDashboardDesdeBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] abDashboard;
        
        public ObtenerDashboardDesdeBDResponse() {
        }
        
        public ObtenerDashboardDesdeBDResponse(byte[] abDashboard) {
            this.abDashboard = abDashboard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutarOperacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EjecutarOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLSalida;
        
        public EjecutarOperacionRequest() {
        }
        
        public EjecutarOperacionRequest(string strXMLEntrada, string strXMLSalida) {
            this.strXMLEntrada = strXMLEntrada;
            this.strXMLSalida = strXMLSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutarOperacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EjecutarOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLSalida;
        
        public EjecutarOperacionResponse() {
        }
        
        public EjecutarOperacionResponse(string strXMLSalida) {
            this.strXMLSalida = strXMLSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarWorkflows", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarWorkflowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLDatos;
        
        public ListarWorkflowsRequest() {
        }
        
        public ListarWorkflowsRequest(string strToken, string strXMLDatos) {
            this.strToken = strToken;
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarWorkflowsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarWorkflowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLDatos;
        
        public ListarWorkflowsResponse() {
        }
        
        public ListarWorkflowsResponse(string strXMLDatos) {
            this.strXMLDatos = strXMLDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerWorkflowDesdeBD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerWorkflowDesdeBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strIdWorkflow;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] abWorkflow;
        
        public ObtenerWorkflowDesdeBDRequest() {
        }
        
        public ObtenerWorkflowDesdeBDRequest(string strIdWorkflow, byte[] abWorkflow) {
            this.strIdWorkflow = strIdWorkflow;
            this.abWorkflow = abWorkflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerWorkflowDesdeBDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerWorkflowDesdeBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] abWorkflow;
        
        public ObtenerWorkflowDesdeBDResponse() {
        }
        
        public ObtenerWorkflowDesdeBDResponse(byte[] abWorkflow) {
            this.abWorkflow = abWorkflow;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFactorySuiteChannel : FactorySuiteTools.wsFactorySuite.IServicioFactorySuite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFactorySuiteClient : System.ServiceModel.ClientBase<FactorySuiteTools.wsFactorySuite.IServicioFactorySuite>, FactorySuiteTools.wsFactorySuite.IServicioFactorySuite {
        
        public ServicioFactorySuiteClient() {
        }
        
        public ServicioFactorySuiteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFactorySuiteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFactorySuiteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFactorySuiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.AutenticarUsuarioResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.AutenticarUsuario(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuario(request);
        }
        
        public string AutenticarUsuario(string Usuario, string Clave, ref string Token, ref string IdUsuario) {
            FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest inValue = new FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest();
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.Token = Token;
            inValue.IdUsuario = IdUsuario;
            FactorySuiteTools.wsFactorySuite.AutenticarUsuarioResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).AutenticarUsuario(inValue);
            Token = retVal.Token;
            IdUsuario = retVal.IdUsuario;
            return retVal.AutenticarUsuarioResult;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.AutenticarUsuarioResponse> AutenticarUsuarioAsync(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuarioAsync(request);
        }
        
        public string AutenticarUsuarioTipoAutenticacionExterna(string strTipoAutenticacion, string Usuario, string Clave) {
            return base.Channel.AutenticarUsuarioTipoAutenticacionExterna(strTipoAutenticacion, Usuario, Clave);
        }
        
        public System.Threading.Tasks.Task<string> AutenticarUsuarioTipoAutenticacionExternaAsync(string strTipoAutenticacion, string Usuario, string Clave) {
            return base.Channel.AutenticarUsuarioTipoAutenticacionExternaAsync(strTipoAutenticacion, Usuario, Clave);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.AutenticarUsuarioFirmaDigital(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest request) {
            return base.Channel.AutenticarUsuarioFirmaDigital(request);
        }
        
        public string AutenticarUsuarioFirmaDigital(string Usuario, string Clave, string strFirmaDigital, ref string Token, ref string IdUsuario) {
            FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest inValue = new FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest();
            inValue.Usuario = Usuario;
            inValue.Clave = Clave;
            inValue.strFirmaDigital = strFirmaDigital;
            inValue.Token = Token;
            inValue.IdUsuario = IdUsuario;
            FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).AutenticarUsuarioFirmaDigital(inValue);
            Token = retVal.Token;
            IdUsuario = retVal.IdUsuario;
            return retVal.AutenticarUsuarioFirmaDigitalResult;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalResponse> AutenticarUsuarioFirmaDigitalAsync(FactorySuiteTools.wsFactorySuite.AutenticarUsuarioFirmaDigitalRequest request) {
            return base.Channel.AutenticarUsuarioFirmaDigitalAsync(request);
        }
        
        public string CerrarSesionUsuario(string Token) {
            return base.Channel.CerrarSesionUsuario(Token);
        }
        
        public System.Threading.Tasks.Task<string> CerrarSesionUsuarioAsync(string Token) {
            return base.Channel.CerrarSesionUsuarioAsync(Token);
        }
        
        public ActividadesLibreria.Design.Data.wsFactorySuite.empleado[] ObtenerLista() {
            return base.Channel.ObtenerLista();
        }
        
        public System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado[]> ObtenerListaAsync() {
            return base.Channel.ObtenerListaAsync();
        }
        
        public ActividadesLibreria.Design.Data.wsFactorySuite.empleado[] ObtenerListaVacia() {
            return base.Channel.ObtenerListaVacia();
        }
        
        public System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado[]> ObtenerListaVaciaAsync() {
            return base.Channel.ObtenerListaVaciaAsync();
        }
        
        public ActividadesLibreria.Design.Data.wsFactorySuite.empleado ObtenerEmpleado(int id) {
            return base.Channel.ObtenerEmpleado(id);
        }
        
        public System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.empleado> ObtenerEmpleadoAsync(int id) {
            return base.Channel.ObtenerEmpleadoAsync(id);
        }
        
        public void ActualizarEmpleado(int id, string cedula, string nombre, int TipoIdentificacion) {
            base.Channel.ActualizarEmpleado(id, cedula, nombre, TipoIdentificacion);
        }
        
        public System.Threading.Tasks.Task ActualizarEmpleadoAsync(int id, string cedula, string nombre, int TipoIdentificacion) {
            return base.Channel.ActualizarEmpleadoAsync(id, cedula, nombre, TipoIdentificacion);
        }
        
        public void EliminarEmpleado(int id) {
            base.Channel.EliminarEmpleado(id);
        }
        
        public System.Threading.Tasks.Task EliminarEmpleadoAsync(int id) {
            return base.Channel.EliminarEmpleadoAsync(id);
        }
        
        public int InsertarEmpleado(string cedula, string nombre, int TipoIdentificacion) {
            return base.Channel.InsertarEmpleado(cedula, nombre, TipoIdentificacion);
        }
        
        public System.Threading.Tasks.Task<int> InsertarEmpleadoAsync(string cedula, string nombre, int TipoIdentificacion) {
            return base.Channel.InsertarEmpleadoAsync(cedula, nombre, TipoIdentificacion);
        }
        
        public ActividadesLibreria.Design.Data.wsFactorySuite.retorno InsertarEmpleadoClase(string cedula, string nombre, int TipoIdentificacion) {
            return base.Channel.InsertarEmpleadoClase(cedula, nombre, TipoIdentificacion);
        }
        
        public System.Threading.Tasks.Task<ActividadesLibreria.Design.Data.wsFactorySuite.retorno> InsertarEmpleadoClaseAsync(string cedula, string nombre, int TipoIdentificacion) {
            return base.Channel.InsertarEmpleadoClaseAsync(cedula, nombre, TipoIdentificacion);
        }
        
        public string EncriptarClaves() {
            return base.Channel.EncriptarClaves();
        }
        
        public System.Threading.Tasks.Task<string> EncriptarClavesAsync() {
            return base.Channel.EncriptarClavesAsync();
        }
        
        public void ActualizarEsquemaFormularios(string[] arrLlavesFormulario) {
            base.Channel.ActualizarEsquemaFormularios(arrLlavesFormulario);
        }
        
        public System.Threading.Tasks.Task ActualizarEsquemaFormulariosAsync(string[] arrLlavesFormulario) {
            return base.Channel.ActualizarEsquemaFormulariosAsync(arrLlavesFormulario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ListarReportesResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ListarReportes(FactorySuiteTools.wsFactorySuite.ListarReportesRequest request) {
            return base.Channel.ListarReportes(request);
        }
        
        public void ListarReportes(string strToken, ref string strXMLDatos) {
            FactorySuiteTools.wsFactorySuite.ListarReportesRequest inValue = new FactorySuiteTools.wsFactorySuite.ListarReportesRequest();
            inValue.strToken = strToken;
            inValue.strXMLDatos = strXMLDatos;
            FactorySuiteTools.wsFactorySuite.ListarReportesResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ListarReportes(inValue);
            strXMLDatos = retVal.strXMLDatos;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarReportesResponse> ListarReportesAsync(FactorySuiteTools.wsFactorySuite.ListarReportesRequest request) {
            return base.Channel.ListarReportesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ConsultarDatosReporte(FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest request) {
            return base.Channel.ConsultarDatosReporte(request);
        }
        
        public void ConsultarDatosReporte(System.Collections.Generic.Dictionary<string, string> RQ, ref string strXMLDatos, ref string strParametrosPorResolver, ref byte[] objDataSet) {
            FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest inValue = new FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest();
            inValue.RQ = RQ;
            inValue.strXMLDatos = strXMLDatos;
            inValue.strParametrosPorResolver = strParametrosPorResolver;
            inValue.objDataSet = objDataSet;
            FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ConsultarDatosReporte(inValue);
            strXMLDatos = retVal.strXMLDatos;
            strParametrosPorResolver = retVal.strParametrosPorResolver;
            objDataSet = retVal.objDataSet;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteResponse> ConsultarDatosReporteAsync(FactorySuiteTools.wsFactorySuite.ConsultarDatosReporteRequest request) {
            return base.Channel.ConsultarDatosReporteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ObtenerReporteDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest request) {
            return base.Channel.ObtenerReporteDesdeBD(request);
        }
        
        public void ObtenerReporteDesdeBD(string strIdReporte, ref byte[] abReporte) {
            FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest inValue = new FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest();
            inValue.strIdReporte = strIdReporte;
            inValue.abReporte = abReporte;
            FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ObtenerReporteDesdeBD(inValue);
            abReporte = retVal.abReporte;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDResponse> ObtenerReporteDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerReporteDesdeBDRequest request) {
            return base.Channel.ObtenerReporteDesdeBDAsync(request);
        }
        
        public void GuardarReporte(string IdReporte, byte[] baLayoutReport) {
            base.Channel.GuardarReporte(IdReporte, baLayoutReport);
        }
        
        public System.Threading.Tasks.Task GuardarReporteAsync(string IdReporte, byte[] baLayoutReport) {
            return base.Channel.GuardarReporteAsync(IdReporte, baLayoutReport);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ListarDashboardsResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ListarDashboards(FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest request) {
            return base.Channel.ListarDashboards(request);
        }
        
        public void ListarDashboards(string strToken, ref string strXMLDatos) {
            FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest inValue = new FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest();
            inValue.strToken = strToken;
            inValue.strXMLDatos = strXMLDatos;
            FactorySuiteTools.wsFactorySuite.ListarDashboardsResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ListarDashboards(inValue);
            strXMLDatos = retVal.strXMLDatos;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarDashboardsResponse> ListarDashboardsAsync(FactorySuiteTools.wsFactorySuite.ListarDashboardsRequest request) {
            return base.Channel.ListarDashboardsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ConsultarDatosDashboard(FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest request) {
            return base.Channel.ConsultarDatosDashboard(request);
        }
        
        public void ConsultarDatosDashboard(System.Collections.Generic.Dictionary<string, string> RQ, ref string strXMLDatos, ref string strParametrosPorResolver, ref byte[] objDataSet) {
            FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest inValue = new FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest();
            inValue.RQ = RQ;
            inValue.strXMLDatos = strXMLDatos;
            inValue.strParametrosPorResolver = strParametrosPorResolver;
            inValue.objDataSet = objDataSet;
            FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ConsultarDatosDashboard(inValue);
            strXMLDatos = retVal.strXMLDatos;
            strParametrosPorResolver = retVal.strParametrosPorResolver;
            objDataSet = retVal.objDataSet;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardResponse> ConsultarDatosDashboardAsync(FactorySuiteTools.wsFactorySuite.ConsultarDatosDashboardRequest request) {
            return base.Channel.ConsultarDatosDashboardAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ObtenerDashboardDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest request) {
            return base.Channel.ObtenerDashboardDesdeBD(request);
        }
        
        public void ObtenerDashboardDesdeBD(string strIdDashboard, ref byte[] abDashboard) {
            FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest inValue = new FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest();
            inValue.strIdDashboard = strIdDashboard;
            inValue.abDashboard = abDashboard;
            FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ObtenerDashboardDesdeBD(inValue);
            abDashboard = retVal.abDashboard;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDResponse> ObtenerDashboardDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerDashboardDesdeBDRequest request) {
            return base.Channel.ObtenerDashboardDesdeBDAsync(request);
        }
        
        public void GuardarDashboard(string IdDashboard, byte[] baLayoutDashboard) {
            base.Channel.GuardarDashboard(IdDashboard, baLayoutDashboard);
        }
        
        public System.Threading.Tasks.Task GuardarDashboardAsync(string IdDashboard, byte[] baLayoutDashboard) {
            return base.Channel.GuardarDashboardAsync(IdDashboard, baLayoutDashboard);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.EjecutarOperacionResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.EjecutarOperacion(FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest request) {
            return base.Channel.EjecutarOperacion(request);
        }
        
        public void EjecutarOperacion(string strXMLEntrada, ref string strXMLSalida) {
            FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest inValue = new FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest();
            inValue.strXMLEntrada = strXMLEntrada;
            inValue.strXMLSalida = strXMLSalida;
            FactorySuiteTools.wsFactorySuite.EjecutarOperacionResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).EjecutarOperacion(inValue);
            strXMLSalida = retVal.strXMLSalida;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.EjecutarOperacionResponse> EjecutarOperacionAsync(FactorySuiteTools.wsFactorySuite.EjecutarOperacionRequest request) {
            return base.Channel.EjecutarOperacionAsync(request);
        }
        
        public string[] EjecutarOperacionMoviles(string strXMLEntrada) {
            return base.Channel.EjecutarOperacionMoviles(strXMLEntrada);
        }
        
        public System.Threading.Tasks.Task<string[]> EjecutarOperacionMovilesAsync(string strXMLEntrada) {
            return base.Channel.EjecutarOperacionMovilesAsync(strXMLEntrada);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ListarWorkflowsResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ListarWorkflows(FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest request) {
            return base.Channel.ListarWorkflows(request);
        }
        
        public void ListarWorkflows(string strToken, ref string strXMLDatos) {
            FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest inValue = new FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest();
            inValue.strToken = strToken;
            inValue.strXMLDatos = strXMLDatos;
            FactorySuiteTools.wsFactorySuite.ListarWorkflowsResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ListarWorkflows(inValue);
            strXMLDatos = retVal.strXMLDatos;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ListarWorkflowsResponse> ListarWorkflowsAsync(FactorySuiteTools.wsFactorySuite.ListarWorkflowsRequest request) {
            return base.Channel.ListarWorkflowsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDResponse FactorySuiteTools.wsFactorySuite.IServicioFactorySuite.ObtenerWorkflowDesdeBD(FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest request) {
            return base.Channel.ObtenerWorkflowDesdeBD(request);
        }
        
        public void ObtenerWorkflowDesdeBD(string strIdWorkflow, ref byte[] abWorkflow) {
            FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest inValue = new FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest();
            inValue.strIdWorkflow = strIdWorkflow;
            inValue.abWorkflow = abWorkflow;
            FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDResponse retVal = ((FactorySuiteTools.wsFactorySuite.IServicioFactorySuite)(this)).ObtenerWorkflowDesdeBD(inValue);
            abWorkflow = retVal.abWorkflow;
        }
        
        public System.Threading.Tasks.Task<FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDResponse> ObtenerWorkflowDesdeBDAsync(FactorySuiteTools.wsFactorySuite.ObtenerWorkflowDesdeBDRequest request) {
            return base.Channel.ObtenerWorkflowDesdeBDAsync(request);
        }
        
        public void GuardarWorkflow(string IdWorkflow, byte[] baLayoutWorkflow) {
            base.Channel.GuardarWorkflow(IdWorkflow, baLayoutWorkflow);
        }
        
        public System.Threading.Tasks.Task GuardarWorkflowAsync(string IdWorkflow, byte[] baLayoutWorkflow) {
            return base.Channel.GuardarWorkflowAsync(IdWorkflow, baLayoutWorkflow);
        }
        
        public string ObtenerListaFormularios() {
            return base.Channel.ObtenerListaFormularios();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaFormulariosAsync() {
            return base.Channel.ObtenerListaFormulariosAsync();
        }
        
        public string ObtenerListaPrioridades() {
            return base.Channel.ObtenerListaPrioridades();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaPrioridadesAsync() {
            return base.Channel.ObtenerListaPrioridadesAsync();
        }
        
        public string ObtenerListaUsuarios() {
            return base.Channel.ObtenerListaUsuarios();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaUsuariosAsync() {
            return base.Channel.ObtenerListaUsuariosAsync();
        }
        
        public string ObtenerListaRoles() {
            return base.Channel.ObtenerListaRoles();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaRolesAsync() {
            return base.Channel.ObtenerListaRolesAsync();
        }
        
        public string ObtenerListaPuestos() {
            return base.Channel.ObtenerListaPuestos();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaPuestosAsync() {
            return base.Channel.ObtenerListaPuestosAsync();
        }
        
        public string ObtenerListaComandos() {
            return base.Channel.ObtenerListaComandos();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaComandosAsync() {
            return base.Channel.ObtenerListaComandosAsync();
        }
        
        public string ObtenerListaEstadosProceso(int IdWorkflow) {
            return base.Channel.ObtenerListaEstadosProceso(IdWorkflow);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerListaEstadosProcesoAsync(int IdWorkflow) {
            return base.Channel.ObtenerListaEstadosProcesoAsync(IdWorkflow);
        }
    }
}
